# Configuration for testing on UCSD dataset
dataset_path: "/path/to/ucsd"
dataset_name: "ucsd"

# Model parameters
temporal_transformer_layers: 2
temporal_heads: 8
clip_length: 16
stride: 8

# Testing parameters
batch_size: 1

# CLIP parameters
image_size: 336
features_list: [6, 12, 18, 24]
feature_map_layers: [0, 1, 2, 3]

# Prompt parameters
n_ctx: 12
depth: 9
t_n_ctx: 4

# Semantic prompts for UCSD dataset anomalies
semantic_prompts:
  - "a person riding a bicycle"
  - "a person on a skateboard" 
  - "a small cart on a walkway"
  - "a person in a wheelchair"
  - "a vehicle on the walkway"
  - "people running"
  - "people fighting"

# Evaluation settings
checkpoint_path: "./checkpoints/shanghaitech/best_model.pth"
results_dir: "./results/ucsd/"
save_visualizations: false

# Post-processing
gaussian_sigma: 4
score_aggregation: "max"  # or "mean"